# Generated by Django 5.2.7 on 2025-10-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('ou_location', models.TextField(verbose_name='OU位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='资产编码')),
                ('sn_code', models.CharField(max_length=50, verbose_name='SN码')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('device_type', models.CharField(default='Default string', max_length=50, verbose_name='设备类型')),
                ('cpu_model', models.CharField(max_length=100, verbose_name='CPU型号')),
                ('memory_size', models.IntegerField(verbose_name='内存大小(GB)')),
                ('os_version', models.CharField(max_length=100, verbose_name='操作系统版本')),
                ('os_internal_version', models.CharField(max_length=50, verbose_name='操作系统内部版本')),
                ('uploader', models.CharField(default='Robot', max_length=50, verbose_name='上传者')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.employee', verbose_name='使用人')),
            ],
            options={
                'verbose_name': '计算机',
                'verbose_name_plural': '计算机',
                'ordering': ['-upload_time'],
            },
        ),
    ]
