# Generated by Django 5.2.7 on 2025-10-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
    ]
