# Generated by Django 5.2.7 on 2025-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20251011_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='employee',
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(default='', max_length=100, verbose_name='计算机名'),
        ),
        migrations.AddField(
            model_name='computer',
            name='error_log',
            field=models.TextField(blank=True, help_text='业务逻辑错误信息', null=True, verbose_name='错误日志'),
        ),
        migrations.AddField(
            model_name='computer',
            name='execution_log',
            field=models.TextField(blank=True, help_text='PowerShell脚本的完整执行日志', null=True, verbose_name='执行日志'),
        ),
        migrations.AddField(
            model_name='computer',
            name='has_errors',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否有错误'),
        ),
        migrations.AddField(
            model_name='computer',
            name='log_size',
            field=models.IntegerField(default=0, verbose_name='日志大小(字节)'),
        ),
        migrations.AddField(
            model_name='computer',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='asset_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='资产编码'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
